import { Raleway, Manrope } from "next/font/google";
import "../styles/globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cyanidium.dev test",
  description: "Generated by Tymchuk",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} ${manrope.variable}`}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Sansation:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
